### ISSUE TITLE
FIles problem.

### ISSUE THREAD

**Issue by rutekoowski** [surenjanath/Spotify-Song-Downloader-PyQt5#1]
Program works really fine, but i have an issue with downloaded songs. They only weigh 15KB (each) and i can't listen to them.
![image](https://github.com/surenjanath/Spotify-Song-Downloader-PyQt5/assets/140883128/2258bdf1-a440-4283-85c1-bebe9fa151e2)
![image](https://github.com/surenjanath/Spotify-Song-Downloader-PyQt5/assets/140883128/67ff2cfe-4ccc-4e84-9c5f-35350284cd04)

**Comment by surenjanath** [comment]
hey thanks can you post the playlist so that i can replicate your issue, as i just tried on myy end its fine.
![image](https://github.com/surenjanath/Spotify-Song-Downloader-PyQt5/assets/42503383/b294f9b0-0b3e-4890-be3f-2c900cad9333)

I used this Playlist : https://open.spotify.com/playlist/37i9dQZF1DX2L0iB23Enbq?si=d8e03fc001264d53

**Comment by rutekoowski** [comment]
yeah, ive tried w this one
[https://open.spotify.com/playlist/37i9dQZF1DX76t638V6CA8?si=108fb9b61f4d45d0](url)

**Comment by surenjanath** [comment]
hey in the new version this is working 

![image](https://github.com/surenjanath/Spotify-Song-Downloader-PyQt5/assets/42503383/fc44856e-660c-44ef-b974-9b5cf32a2f45)
