### ISSUE TITLE
Random songs not downloading

### ISSUE THREAD

**Issue by JustaguyPY** [surenjanath/Spotify-Song-Downloader-PyQt5#19]
Only some songs are downloaded, the others haves this error:
![image](https://github.com/surenjanath/Spotify-Song-Downloader-PyQt5/assets/138535056/d59c80a6-e6db-41cd-8204-bf71792f261a)

**Comment by Ayobamidele** [comment]
I noticed the same thing using the application today

**Comment by Ayobamidele** [comment]
Hi there! 👋 It looks like you're having some trouble downloading songs from Spotify. 😕 Let me explain what's going on and how you can fix it. 🛠

- The code you're using tries to download songs using two methods: 
  - The first method uses `api.spotifydown.com` to get the download link. 🎵
  - The second method uses YouTube to get the download link. 📺
Sometimes, the first method fails because the service is down or changes its API. 😢 When that happens, the code tries the second method, but that also fails because of a 403 error. 😱
- A 403 error means that the server is denying your request. 😞
This is because the code uses `corsproxy.io` to bypass the cross-origin restrictions. 🚫However, `corsproxy.io` requires you to create an account and follow some instructions to use their service. 🙋‍♂️ If you don't do that, you won't be able to access the YouTube download link. 😭

So, how can you solve this problem? Here are some options: 🤔

- Option 1: Create an account on `corsproxy.io` and follow their instructions to use their service with the `generate_Analyze_id` function. This might take some time to set up, but once you do, it should work. 👍
- Option 2: Use a different tool to download songs from YouTube, such as `ytmdl`. This might be simpler and faster than using `corsproxy.io`. 👌

I hope this helps you understand the issue and how to fix it. 😊 If you have any other questions or need more assistance, feel free to ask! 😄

**Comment by wesux** [comment]
-----> "Sometimes, the first method fails because the service is down or changes its API."
Will this rectify itself If you try the download again at another time? Does the changed API get fixed?

**Comment by surenjanath** [comment]
Hopefully New update fixes this. v2.1.2
